"""empty message

Revision ID: 12e97b5c8ac8
Revises: 12bda49a4239
Create Date: 2025-08-12 23:02:28.100803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12e97b5c8ac8'
down_revision: Union[str, Sequence[str], None] = '12bda49a4239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squads', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'squads', ['link_to_squad'])
    op.drop_column('squads', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squads', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'squads', type_='unique')
    op.drop_column('squads', 'photo_url')
    # ### end Alembic commands ###
